//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define IDD_SETTINGS_OFFSET_INITIAL     0
#define IDD_DIALER_OFFSET_1             1
#define IDD_RINGIN_OFFSET_1             15
#define IDD_MAIN                        102
#define IDS_STATUSBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_MENU_CONTACT                129
#define IDR_MENU_MESSAGES               130
#define IDR_MENU_TABS                   131
#define IDR_MENU_TRAY                   132
#define IDD_ACCOUNT                     133
#define IDD_ACCOUNT_CUSTOM              134
#define IDD_ACCOUNT_PIN                 135
#define IDD_ACCOUNT_REG                 136
#define IDD_ADD                         137
#define IDD_BUTTONS                     138
#define IDD_CALLS                       139
#define IDD_CONFERNCE                   140
#define IDD_CONTACTS                    141
#define IDD_DIALER                      142
#define IDD_MESSAGES                    143
#define IDD_REG_STEP1                   144
#define IDD_REG_STEP2                   145
#define IDD_REG_STEP3                   146
#define IDD_RINGIN                      147
#define IDD_SETTINGS                    148
#define IDD_TRANSFER                    149
#define IDI_ACTIVE                      150
#define IDI_ATTENDED_TRANSFER           151
#define IDI_AWAY                        152
#define IDI_BLANK                       153
#define IDI_BUSY                        154
#define IDI_CALL_IN                     155
#define IDI_CALL_MISS                   156
#define IDI_CALL_OUT                    157
#define IDI_CLOSE                       158
#define IDI_CLOSE_2                     159
#define IDI_DEFAULT                     160
#define IDI_END                         161
#define IDI_EXIT                        162
#define IDI_HOLD                        163
#define IDI_INACTIVE                    164
#define IDI_LOGO                        165
#define IDI_MESSAGE                     166
#define IDI_MUTE                        167
#define IDI_MUTE_INPUT                  168
#define IDI_MUTE_OUTPUT                 169
#define IDI_MUTED                       170
#define IDI_MUTED_INPUT                 171
#define IDI_MUTED_OUTPUT                172
#define IDI_OFFLINE                     173
#define IDI_ONLINE                      174
#define IDI_TRANSFER                    175
#define IDI_TRAY                        176
#define IDI_UNKNOWN                     177
#define PAGE_WIDTH                      177
#define IDI_VIDEO                       178
#define IDD_DIALOG1                     179
#define STR_SZ                          256
#define IDC_ANSWER                      1000
#define IDC_ATTENDED_TRANSFER           1001
#define IDC_ANSWER_BOX_RANDOM           1002
#define IDC_AUDIO_CODECS                1003
#define IDC_AUDIO_CODECS_ALL            1004
#define IDC_AUTO_ANSWER                 1005
#define IDC_BALANCE                     1006
#define IDC_BITRATE_263                 1007
#define IDC_BITRATE_264                 1008
#define IDC_BROWSE                      1009
#define IDC_BROWSE_INI                  1010
#define IDC_BUTTON_AR                   1011
#define IDC_BUTTON_CN                   1012
#define IDC_BUTTON_EN                   1013
#define IDC_BUTTON_FLOOR                1014
#define IDC_BUTTON_FR                   1015
#define IDC_BUTTON_HAND                 1016
#define IDC_BUTTON_MUTE                 1017
#define IDC_BUTTON_MUTE_INPUT           1018
#define IDC_BUTTON_MUTE_OUTPUT          1019
#define IDC_BUTTON_RU                   1020
#define IDC_BUTTON_SP                   1021
#define IDC_CALL                        1022
#define IDC_CALL_END                    1023
#define IDC_CALL_SKYPE                  1024
#define IDC_CALLER_ADDR                 1025
#define IDC_CALLER_NAME                 1026
#define IDC_CALLS                       1027
#define IDC_CLEAR                       1028
#define IDC_CLOSE_ALL                   1029
#define IDC_CONTACTS                    1030
#define IDC_CUSTOM_INI                  1031
#define IDC_DECLINE                     1032
#define IDC_DEFAULT                     1033
#define IDC_DEFAULT_INI                 1034
#define IDC_DELETE                      1035
#define IDC_DENY_INCOMING               1036
#define IDC_DIRECTORY                   1037
#define IDC_DISABLE_H263                1038
#define IDC_DISABLE_H264                1039
#define IDC_ENABLE_LOCAL                1040
#define IDC_EC                          1041
#define IDC_EDIT_API_ID                 1042
#define IDC_EDIT_AUTHID                 1043
#define IDC_EDIT_CONFERENCE_CODE        1044
#define IDC_EDIT_DISPLAYNAME            1045
#define IDC_EDIT_DOMAIN                 1046
#define IDC_EDIT_NAME                   1047
#define IDC_EDIT_NUMBER                 1048
#define IDC_EDIT_PASSWORD               1049
#define IDC_EDIT_PORT                   1050
#define IDC_EDIT_PROXY                  1051
#define IDC_EDIT_SERVER                 1052
#define IDC_EDIT_USERNAME               1053
#define IDC_ENABLE_LOG                  1054
#define IDC_EDIT_TRANSFEREXT            1054
#define IDC_END                         1055
#define IDC_FORCE_CODEC                 1056
#define IDC_HOLD                        1057
#define IDC_ICE                         1058
#define IDC_IGNORE                      1059
#define IDC_KEY_0                       1060
#define IDC_KEY_1                       1061
#define IDC_KEY_2                       1062
#define IDC_KEY_3                       1063
#define IDC_KEY_4                       1064
#define IDC_KEY_5                       1065
#define IDC_KEY_6                       1066
#define IDC_KEY_7                       1067
#define IDC_KEY_8                       1068
#define IDC_KEY_9                       1069
#define IDC_KEY_GRATE                   1070
#define IDC_KEY_PLUS                    1071
#define IDC_KEY_STAR                    1072
#define IDC_LAST_CALL                   1073
#define IDC_LIST                        1074
#define IDC_LOCAL_DTMF                  1075
#define IDC_MESSAGE                     1076
#define IDC_MICROPHONE                  1077
#define IDC_NUMBER                      1078
#define IDC_PRESENCE                    1079
#define IDC_PREVIEW                     1080
#define IDC_PROFILE                     1081
#define IDC_PUBLIC_ADDR                 1082
#define IDC_PUBLISH                     1083
#define IDC_REG_CODE                    1084
#define IDC_REG_COUNTRY                 1085
#define IDC_REG_EMAIL                   1086
#define IDC_REG_NUMBER                  1087
#define IDC_REG_PASS1                   1088
#define IDC_REG_PASS2                   1089
#define IDC_REMEMBER_PASSWORD           1090
#define IDC_REWRITE                     1091
#define IDC_RING                        1092
#define IDC_RINGING_SOUND               1093
#define IDC_SINGLE_MODE                 1094
#define IDC_SPEAKERS                    1095
#define IDC_SPIN_MODIFY                 1096
#define IDC_SPIN_ORDER                  1097
#define IDC_SRTP                        1098
#define IDC_STUN                        1099
#define IDC_SYSLINK_AUDIO_CODECS        1100
#define IDC_SYSLINK_AUTHID              1101
#define IDC_SYSLINK_AUTO_ANSWER         1102
#define IDC_SYSLINK_DELETE              1103
#define IDC_SYSLINK_DENY_INCOMING       1104
#define IDC_SYSLINK_DIRECTORY           1105
#define IDC_SYSLINK_DISABLE_H263        1106
#define IDC_SYSLINK_DISABLE_H264        1107
#define IDC_SYSLINK_DISABLE_LOCAL       1108
#define IDC_SYSLINK_DISPLAY_PASSWORD    1109
#define IDC_SYSLINK_DOMAIN              1110
#define IDC_SYSLINK_EC                  1111
#define IDC_SYSLINK_ENABLE_LOG          1112
#define IDC_SYSLINK_ENCRYPTION          1113
#define IDC_SYSLINK_FORCE_CODEC         1114
#define IDC_SYSLINK_ICE                 1115
#define IDC_SYSLINK_LOCAL_DTMF          1116
#define IDC_SYSLINK_LOCAL_PORT          1117
#define IDC_SYSLINK_NAME                1118
#define IDC_SYSLINK_PASSWORD            1119
#define IDC_SYSLINK_PREFIX              1120
#define IDC_SYSLINK_PUBLIC_ADDRESS      1121
#define IDC_SYSLINK_PUBLISH_PRESENCE    1122
#define IDC_SYSLINK_REG                 1123
#define IDC_SYSLINK_REWRITE             1124
#define IDC_SYSLINK_RINGING_SOUND       1125
#define IDC_SYSLINK_SINGLE_MODE         1126
#define IDC_SYSLINK_SIP_PROXY           1127
#define IDC_SYSLINK_SIP_SERVER          1128
#define IDC_SYSLINK_ANSWER_BOX_RANDOM   1129
#define IDC_SYSLINK_STUN_SERVER         1130
#define IDC_SYSLINK_TRANSPORT           1131
#define IDC_SYSLINK_USERNAME            1132
#define IDC_SYSLINK_VAD                 1133
#define IDC_TAB                         1134
#define IDC_TRANSFER                    1135
#define IDC_TRANSPORT                   1136
#define IDC_UPDATES_INTERVAL            1137
#define IDC_VAD                         1138
#define IDC_VID_CAP_DEV                 1139
#define IDC_VIDEO                       1140
#define IDC_VIDEO_CALL                  1141
#define IDC_VIDEO_CODEC                 1142
#define IDC_VOLUME_INPUT                1143
#define IDC_VOLUME_OUTPUT               1144
#define IDC_URL_INCOMING_CALL           1145
#define IDC_STUN_CHECKBOX               1146
#define IDC_BALANCE_URL                 1147
#define IDC_CHECK1                      1148
#define IDC_AUTO_TRANSFER_ENABLE        1148
#define ID_ACCOUNT_ADD                  32771
#define ID_ADD                          32775
#define ID_ALWAYS_ON_TOP                32776
#define ID_CALL                         32777
#define ID_CALL_PICKUP                  32778
#define ID_CHAT                         32779
#define ID_CLOSEALLTABS                 32780
#define ID_COPY                         32781
#define ID_DELETE                       32782
#define ID_EDIT                         32783
#define ID_EXIT                         32784
#define ID_GOTOLASTTAB                  32785
#define ID_LOG                          32786
#define ID_DONATE                       32787
#define ID_SELECT_ALL                   32788
#define ID_SETTINGS                     32789
#define ID_VIDEOCALL                    32790
#define ID_WEBSITE                      32791
#define ID_ACCOUNT_CHANGE_RANGE         40000
#define ID_ACCOUNT_EDIT_RANGE           40100
#define ID_ATTENDED_TRANSFER_RANGE      40200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1149
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
